config/routes.rb
Rails.application.routes.draw do
  resources :scripts

  resources :stanzas
  resources :author

  get 'script/new'

  get 'script/create'

  get 'script/find'

  get 'home/index'

  root 'home#index'

  post "stanzas/:id" => "stanzas#create"

  devise_for :authors, :controllers => { sessions: 'my_sessions',
    registrations: 'registrations' },
                       :path_names => {:sign_up => "register", 
                                      :sign_in => "login", 
                                      :sign_out => "logout",
                                      :settings => "settings"}

end

app/models/author.rb
class Author < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  require 'home_helper'
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  validates :username,
  :uniqueness => {
    :case_sensitive => false
  }, presence: true
  has_many :stanzas
  has_many :scripts
  has_many :whispers
end

app/models/cycdraft.rb
class Cycdraft < ActiveRecord::Base
end

app/models/cycwrite.rb
class Cycwrite < ActiveRecord::Base
end

app/models/script.rb
class Script < ActiveRecord::Base
	belongs_to :author
	has_many :stanzas
end

app/models/stanza.rb
class Stanza < ActiveRecord::Base
	has_many :whispers
	belongs_to :script
	belongs_to :author
end

app/models/whisper.rb
class Whisper < ActiveRecord::Base
	belongs_to :stanza
	has_one :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_params, if: :devise_controller?

end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
  before_filter :authenticate_author!

  def show
    @author = Author.find(params[:id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@scripts = Script.all
  end
end

app/controllers/my_sessions_controller.rb
class MySessionsController < Devise::SessionsController

  before_filter :configure_permitted_params


  protected
    def configure_permitted_params
        devise_parameter_sanitizer.for(:sign_in) do |u| 
          u.permit(:email, :password, :remember_me)
        end
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
  before_filter :configure_permitted_params

  protected
    def configure_permitted_params
      devise_parameter_sanitizer.for(:sign_in) do |u| 
        u.permit(:email, :password, :remember_me)
      end
      devise_parameter_sanitizer.for(:sign_up) do |u|
        u.permit(:username, :email, 
        	:password, :password_confirmation)
      end
      devise_parameter_sanitizer.for(:account_update) do |u|
        u.permit(:username, :bio,
          :email, :password, :password_confirmation, :current_password)
      end
    end

end

app/controllers/scripts_controller.rb
class ScriptsController < ApplicationController
  before_action :set_script, only: [:show, :edit, :update, :destroy]

  def index
    @scripts = Script.all
  end

  def show
    @Stanza = Stanza.new
  end

  def new
    @script = Script.new
  end

  def edit
  end

  def create
    @script = Script.new(script_params)
    @script.votes = 1
    @script.num_of_stanzas = 0
    @script.author_id = current_author.id
    if @script.save
      redirect_to script_path(@script.id)
    else
      flash[:error] = @script.erros.full_messages.to_sentence
      redirect_to new_script_path
    end
  end

  def update
    @script.update(script_params)
  end

  def destroy
    @script.destroy
  end

  private
    def set_script
      @script = Script.find(params[:id])
    end

    def script_params
      params.require(:script).permit(:title, :genre, :preface)
    end

end

app/controllers/stanza_controller.rb
class StanzaController < ApplicationController
	def new
		@Stanza = Stanza.new
	end

	def create
		@Stanza = Stanza.new(stanza_params)
		@Stanza.author_id = current_author.author_id
		@Script = Script.find(@Stanza.script_id)
		@Script.num_of_stanzas += 1
		@Stanza.stanza_number = @Script.num_of_stanzas
		if @Stanza.save
			redirect_path_to script_path(@Script.id)
		else
			flash[:error] = @Stanzas.erros.full_messages.to_sentence
      		redirect_to script_path(@Script.id)
      	end
	end

	def show
	end
	
	def edit
	end
	
	def update
		@Stanza.update(stanza_params)
	end
	
	def destroy
		@Stanza.destroy
	end
	
	private
		def stanza_params
			params.require(:stanza).permit(:content, :script_id)
		end

		def set_stanza
			@Stanza = Stanza.find(params[:id])
		end

end

app/controllers/stanzas_controller.rb
class StanzasController < ApplicationController
	def new
		@Stanza = Stanza.new
	end

	def create
		@Stanza = Stanza.new(stanza_params)
		@Stanza.author_id = current_author.id
		@Script = Script.find(@Stanza.script_id)
		@Script.num_of_stanzas = @Script.num_of_stanzas + 1
		@Script.save
		@Stanza.stanza_number = @Script.num_of_stanzas
		if @Stanza.save
			redirect_to script_path(@Script.id)
		else
			flash[:error] = @Stanza.erros.full_messages.to_sentence
      		redirect_to script_path(@Script.id)
      	end
	end

	def show
	end
	
	def edit
	end
	
	def update
		@Stanza.update(stanza_params)
	end
	
	def destroy
		@Stanza.destroy
	end
	
	private
		def stanza_params
			params.require(:stanza).permit(:content, :script_id)
		end

		def set_stanza
			@Stanza = Stanza.find(params[:id])
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-block">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <strong>#{sentence}</strong>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def resource_name
    :author
  end

  def resource
    @resource ||= Author.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:author]
  end
end

app/helpers/my_sessions_helper.rb
module MySessionsHelper
end

app/helpers/scripts_helper.rb
module ScriptsHelper
  def resource_name
	:stanzas
  end

  def resource
  	@Stanza ||= Stanza.new
  end
end

app/helpers/stanza_helper.rb
module StanzaHelper
end

app/helpers/stanzas_helper.rb
module StanzasHelper
end

app/views/author/_script.html.erb
<td><%= script.title %></td>
<td><%= script.genre %></td>
<td><%= script.num_of_stanzas %></td>
<td><%= script.votes %></td>
<td><%= script.author %></td>

app/views/author/show.html.erb
<div class="container">
	<div class="page-header">
		<h2><%= @author.username %> <small>
			<% if author_signed_in? %>
    			<% if current_author.id == @author.id %>
    				<%= link_to edit_author_registration_path do %>
    					<span class="label label-info">Edit Profile</span>
    				<% end %>
    			<% end %>
    		<% end %>
		</small></h2>
	</div>
	<div class="row">
	      <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
	        <ul class="nav nav-tabs" id="hometabs">
	          <li class="active"><a href="#biography" data-toggle="tab">Biography</a></li>
	          <li><a href="#scripts" data-toggle="tab">Scripts</a></li>
	          <li><a href="#contributions" data-toggle="tab">Contributions</a></li>
	        </ul>
	        <div class="tab-content" id="content">
		        <div class="tab-pane fade in active" id="biography">
		        	<br>
	            	<div class="well">
	            		<% if @author.bio.presence %>
	            			<%= @author.bio %>
	            		<% else %>
	            			<p><%= @author.username %> is a writer.</p>
	            		<% end %>
	            	</div>
		        </div>
		        <div class="tab-pane fade" id="scripts">
		          	<br />
		            <% if @author.scripts.presence %>
						<table class="table table-hover">
							<thead>
							    <tr>
							      <th>Title</th>
							      <th>Genre</th>
							      <th>Stanzas</th>
							      <th>Votes</th>
							    </tr>
							</thead>
							<tbody>
								<% @author.scripts.each do |script| %>
								<tr class="clickableRow" href="../scripts/<%= script.id %>" style="cursor:pointer;">
									<td><%= script.title %></td>
									<td><%= script.genre %></td>
									<td><%= script.num_of_stanzas %></td>
									<td><%= script.votes %></td>
								</tr>
								<% end %>
							</tbody>
						</table>
					<% else %>
						<h4><%= @author.username %> has no scripts :(</h4>
					<% end %>
		        </div>
		        <div class="tab-pane fade" id="contributions">
		            <% if @author.stanzas.presence %>
		            <table class="table table-striped">
		                <thead>
		                  <tr>
		                  	<th>Content</th>
		                  	<th>Location</th>
		                    <th>Script</th>
		                  </tr>
		                </thead>
		                <tbody>
			            	<% @author.stanzas.each do |stanza| %>
								<tr>
									<td><%= stanza.content %></td>
									<td><%= stanza.stanza_number %></td>
									<td><i><q><%= link_to stanza.script.title, stanza.script %></q></i></td>
								</tr>
							<% end %>
						</tbody>
					</table>
					<% else %>
						<h4>Author has made no contributions.</h4>
					<% end %>
		        </div>
		    </div>
	      </div>
	</div>
	
	<% if false %>
		<h4><%= @trainer.name%>'s Pokemons</h4>
		<table>
		  <thead>
		    <tr>
		      <th>Pokemon</th>
		      <th>Level</th>
		      <th>Health</th>
		      <th>Attack!</th>
		    </tr>
		  </thead>
		<tbody>
			<% @trainer.pokemons.each do |pokemon| %>
			<tr>
				<td><%= pokemon.name %></td>
				<td><%= pokemon.level %></td>
				<td><%= pokemon.health %></td>
				<td><%= button_to "Damage!", damage_path(id: pokemon), :class => "button small", :method => :patch %></td>
			</tr>
			<% end %>
		</tbody>
	<% end %>
	<% if false %>
		<h4><%= @trainer.name %> has no pokemons :(</h4>
	<% end %>
</div>
<!-- Allows clickable rows. -->
<script type="text/javascript">
	jQuery(document).ready(function($) {
	      $(".clickableRow").click(function() {
	            window.document.location = $(this).attr("href");
	      });
	});
</script>

app/views/home/index.html.erb
<head>
</head>
<div style="height:30px;">
</div>
<div class="container" style="background-color:transparent !important;">
  <% if !author_signed_in? %>
    <div class="jumbotron">
    <h1>What is MadScript?</h1>
    <p>A CRUD application to stimulate a collaboration between writers. Users can sign up for FREE. If a user has yet to sign up, then the user is only allowed to see the scripts therefore missing out on taking part of great community involvement.</p>
    <p>A user, also known as an author, can start his/her own <b><i>Script!</i></b> The author can also contribute to the work of others by continually adding <b><i>Stanzas</i></b> to any script created by other authors.</p>
    <p>Below, you can see some of the <b><i>Scripts</i></b> community authors have already contributed to! Don't wait any longer, join us!</p>
      <p class="text-center">
        <%= link_to "Start Writing Now", new_author_registration_path, class: "btn btn-lg btn-info" %>
      </p>
    </div>
  <% end %>
    <div class="row">
      <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
        <ul class="nav nav-tabs" id="hometabs">
          <li class="active"><a href="#hot" data-toggle="tab">Trending</a></li>
          <li><a href="#new" data-toggle="tab">New</a></li>
          <% if author_signed_in? %>
            <li><a href="#groups" data-toggle="tab">Groups</a></li>
          <% end %>
        </ul>
        <div class="tab-content" id="content">
          <div class="tab-pane fade in active" id="hot">
            <br>
              <table class="table table-hover">
                <thead>
                  <tr>
                    <th>Author</th>
                    <th>Title</th>
                    <th>Genre</th>
                    <th>Stanzas</th>
                    <th>Votes</th>
                  </tr>
                </thead>
                <tbody>
                  <% Script.find_each do |script| %>
                    <tr class="clickableRow" href="../scripts/<%= script.id %>" style="cursor:pointer;">
                      <td><%= script.author.username %></td>
                      <td><%= script.title %></td>
                      <td><%= script.genre %></td>
                      <td><%= script.num_of_stanzas %></td>
                      <td><%= script.votes %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          <div class="tab-pane fade" id="new">
            <h4>Most recent <b><i>Scripts</i></b> will be displayed.</h4>
          </div>
          <div class="tab-pane fade" id="groups">
            <h4>Feature coming soon.</h4>
            <p>If the <i>Author</i> is part of a <i>Group</i> then there will be a list of <i>Groups</i> the <i>Author</i> belongs in.</p>
            <p>Else, there will be a section showcasing <i>Groups</i> the <i>Author</i> might be interested in!</p>
          </div>
        </div>
      </div>
    <% if author_signed_in? %>
      <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title text-center">Start writing, <%= current_author.username %>!</h3>
          </div>
          <div class="panel-body">
            <p>
              <div class="input-group">
                <div class="input-group-btn">
                  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">Search <span class="caret"></span></button>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#"><i>Author</i></a></li>
                    <li><a href="#"><i>Script</i></a></li>
                    <li><a href="#"><i>Group</i></a></li>
                    <li class="divider"></li>
                    <li><a href="#">Partners</a></li>
                  </ul>
                </div><!-- /btn-group -->
                <input type="text" class="form-control" placeholder="Coming soon...">
              </div><!-- /input-group -->
            </p>
            <hr>
            <p><%= button_to "Author a new Script!", new_script_path, :class => "btn btn-warning", :method => :get, :style => "width:100%" %></p>
            <p><button style="width:100%" type="button" class="btn btn-primary">Host a new <i>Group</i>!</button></p>
          </div>
        </div>
      </div>
    </div>
<hr />
  </div>
  <% end %>
</div>

<script type="text/javascript">
  jQuery(document).ready(function($) {
        $(".clickableRow").click(function() {
              window.document.location = $(this).attr("href");
        });
  });
</script>

app/views/scripts/_form.html.erb
<%= form_for(@script) do |f| %>
  <% if @script.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@script.errors.count, "error") %> prohibited this script from being saved:</h2>

      <ul>
      <% @script.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scripts/_script.html.erb
<td><%= script.title %></td>
<td><%= script.genre %></td>
<td><%= script.num_of_stanzas %></td>
<td><%= script.votes %></td>

app/views/scripts/edit.html.erb
<h1>Editing script</h1>

<%= render 'form' %>

<%= link_to 'Show', @script %> |
<%= link_to 'Back', scripts_path %>

app/views/scripts/index.html.erb
<h1>Listing scripts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scripts.each do |script| %>
      <tr>
        <td><%= link_to 'Show', script %></td>
        <td><%= link_to 'Edit', edit_script_path(script) %></td>
        <td><%= link_to 'Destroy', script, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Script', new_script_path %>

app/views/scripts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-offset-4 col-lg-4 col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-8 col-xs-offset-2">
		<h1 class="text-center">New Script</h1>

		<%= form_for @script do |f| %>
		<div class="form-group">
			<%= f.label :title %><br />
			<%= f.text_field :title, {class: "form-control"}%>
		</div>
		<div class="form-group">
			<%= f.label :genre %> 
			<%= f.select :genre, [['Song', 'Song'], ['Poetry', 'Poetry'], ['Story', 'Story'], ['Novel', 'Novel'], ['Alternative', 'Alternative']], {label: "Script Genre"}, {class: "form-control"} %>
		</div>
		<div class="form-group">
			<%= f.label :preface %>
			<%= f.text_area :preface, {class: "form-control", style: "resize:vertical;"} %>
		</div>
		<div class="form-group">
			<%= f.submit "Write", {class: "btn btn-warning"}%>
		</div>
		<% end %>

		<%= link_to 'Back', scripts_path %>
	</div>
  </div>
</div>

app/views/scripts/show.html.erb
<div class="container">
	<p id="notice"><%= notice %></p>
	<div class="page-header">
 		<h1><i><%= @script.title %></i> <small>
 			<% if author_signed_in? %>
	 			<% if current_author.id == @script.author.id %>
					<%= link_to edit_script_path(@script) do %>
						<span data-toggle="tooltip" data-placement="top" title="edit title" class="label label-default" style="a:hover {text-decoration:none;}">Edit</span> 
					<% end %>
				<% end %>
			<% end %>
 			<span data-toggle="tooltip" data-placement="top" title="genre"class="label label-warning"><%= @script.genre %></span> 
 			<%= link_to @script.author do %>
 				<span data-toggle="tooltip" data-placement="top" title="author" class="label label-primary" style="a:hover {text-decoration:none;}"><%= @script.author.username %></span>
 			<% end %>
 		</small>
 		</h1>
	</div>
	<div class="row">
	      <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
	        <ul class="nav nav-tabs" id="hometabs">
	          <li class="active"><a href="#script" data-toggle="tab">Script</a></li>
	          <li><a href="#description" data-toggle="tab">Preface</a></li>
	          <li><a href="#whispers" data-toggle="tab">Whispers</a></li>
	        </ul>
	        <div class="tab-content" id="content">
	          <div class="tab-pane fade in active" id="script">
		          	<h3>Stanzas</h3>
		          	<div class="panel panel-default">
			            <% if @script.stanzas.presence %>
				            <table class="table table-striped">
				                <thead>
				                  <tr>
				                  	<th>Line</th>
				                    <th>Content</th>
				                    <th>Author</th>
				                  </tr>
				                </thead>
				                <tbody>
				            	<% @script.stanzas.each do |stanza| %>
									<tr>
										<td><%= stanza.stanza_number %></td>
										<td><%= stanza.content %></td>
										<td><%= link_to stanza.author.username, stanza.author%></td>
									</tr>
								<% end %>
				                </tbody>
			            	</table>
						<% else %>
							<p>This script is blank...</p>
			            <% end %>
		            </div>
	          	</div>
	          <div class="tab-pane fade" id="description">
	          	<br />
	            <div class="well">
	            	<p style="font-size:1.5em;"><%= @script.preface %></p>
	            </div>
	          </div>
	          <div class="tab-pane fade" id="whispers">
	            <h4>Discussion developed from the <b><i>Script</i></b> connected to certain <b><i>Stanzas</i></b>. Coming soon!</h4>
	          </div>
	        </div>
	        <hr>
	      	</div>
	<% if author_signed_in? %>
	<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h3 class="panel-title text-center">Start writing! </h3>
			</div>
			<div class="panel-body">
			<%= form_for @Stanza, :url => stanza_path, :html => {:method => :post} do |f| %>
				<div class="form-group">
					<%= f.label :content %>
						<%= f.text_area :content, {class: "form-control", style: "resize:vertical;"} %>
						<%= f.hidden_field :script_id, :value => @script.id %>
				</div>
				<div class="form-group">
					<%= f.submit "add more", {class: "btn btn-info"}%>
				<% end %>
				</div>
				
				</div>	
			</div>
		</div>
	<% end %>
	</div>
</div>
<script type="text/javascript">
    $(function () {
        $("[data-toggle='tooltip']").tooltip();
    });
</script>