config/routes.rb
Rails.application.routes.draw do
  resources :scripts

  resources :stanzas
  resources :author

  get 'script/new'

  get 'script/create'

  get 'script/find'

  get 'home/index'

  root 'home#index'

  post "stanzas/:id" => "stanzas#create"

  devise_for :authors, :controllers => { sessions: 'my_sessions',
    registrations: 'registrations' },
                       :path_names => {:sign_up => "register", 
                                      :sign_in => "login", 
                                      :sign_out => "logout",
                                      :settings => "settings"}

end

app/models/author.rb
class Author < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  require 'home_helper'
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  validates :username,
  :uniqueness => {
    :case_sensitive => false
  }, presence: true
  has_many :stanzas
  has_many :scripts
  has_many :whispers
end

app/models/cycdraft.rb
class Cycdraft < ActiveRecord::Base
end

app/models/cycwrite.rb
class Cycwrite < ActiveRecord::Base
end

app/models/script.rb
class Script < ActiveRecord::Base
	belongs_to :author
	has_many :stanzas
end

app/models/stanza.rb
class Stanza < ActiveRecord::Base
	has_many :whispers
	belongs_to :script
	belongs_to :author
end

app/models/whisper.rb
class Whisper < ActiveRecord::Base
	belongs_to :stanza
	has_one :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_params, if: :devise_controller?

end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
  before_filter :authenticate_author!

  def show
    @author = Author.find(params[:id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@scripts = Script.all
  end
end

app/controllers/scripts_controller.rb
class ScriptsController < ApplicationController
  before_action :set_script, only: [:show, :edit, :update, :destroy]

  def index
    @scripts = Script.all
  end

  def show
    @Stanza = Stanza.new
  end

  def new
    @script = Script.new
  end

  def edit
  end

  def create
    @script = Script.new(script_params)
    @script.votes = 1
    @script.num_of_stanzas = 0
    @script.author_id = current_author.id
    if @script.save
      redirect_to script_path(@script.id)
    else
      flash[:error] = @script.erros.full_messages.to_sentence
      redirect_to new_script_path
    end
  end

  def update
    @script.update(script_params)
  end

  def destroy
    @script.destroy
  end

  private
    def set_script
      @script = Script.find(params[:id])
    end

    def script_params
      params.require(:script).permit(:title, :genre, :preface)
    end

end

app/controllers/stanza_controller.rb
class StanzaController < ApplicationController
	def new
		@Stanza = Stanza.new
	end

	def create
		@Stanza = Stanza.new(stanza_params)
		@Stanza.author_id = current_author.author_id
		@Script = Script.find(@Stanza.script_id)
		@Script.num_of_stanzas += 1
		@Stanza.stanza_number = @Script.num_of_stanzas
		if @Stanza.save
			redirect_path_to script_path(@Script.id)
		else
			flash[:error] = @Stanzas.erros.full_messages.to_sentence
      		redirect_to script_path(@Script.id)
      	end
	end

	def show
	end
	
	def edit
	end
	
	def update
		@Stanza.update(stanza_params)
	end
	
	def destroy
		@Stanza.destroy
	end
	
	private
		def stanza_params
			params.require(:stanza).permit(:content, :script_id)
		end

		def set_stanza
			@Stanza = Stanza.find(params[:id])
		end

end

app/controllers/stanzas_controller.rb
class StanzasController < ApplicationController
	def new
		@Stanza = Stanza.new
	end

	def create
		@Stanza = Stanza.new(stanza_params)
		@Stanza.author_id = current_author.id
		@Script = Script.find(@Stanza.script_id)
		@Script.num_of_stanzas = @Script.num_of_stanzas + 1
		@Script.save
		@Stanza.stanza_number = @Script.num_of_stanzas
		if @Stanza.save
			redirect_to script_path(@Script.id)
		else
			flash[:error] = @Stanza.erros.full_messages.to_sentence
      		redirect_to script_path(@Script.id)
      	end
	end

	def show
	end
	
	def edit
	end
	
	def update
		@Stanza.update(stanza_params)
	end
	
	def destroy
		@Stanza.destroy
	end
	
	private
		def stanza_params
			params.require(:stanza).permit(:content, :script_id)
		end

		def set_stanza
			@Stanza = Stanza.find(params[:id])
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-block">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <strong>#{sentence}</strong>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def resource_name
    :author
  end

  def resource
    @resource ||= Author.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:author]
  end
end

app/helpers/my_sessions_helper.rb
module MySessionsHelper
end

app/helpers/scripts_helper.rb
module ScriptsHelper
  def resource_name
	:stanzas
  end

  def resource
  	@Stanza ||= Stanza.new
  end
end

app/helpers/stanza_helper.rb
module StanzaHelper
end

app/helpers/stanzas_helper.rb
module StanzasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag params[:controller] %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">MadScript</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li class="page-scroll">
                        <a href="#">Explore</a>
                    </li>
                    <li class="page-scroll">
                        <a href="#">About</a>
                    </li>
                    <% if author_signed_in? %>
	                    <li class="dropdown">
				          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Hello, <%= current_author.username %> <span class="caret"></span></a>
				          <ul class="dropdown-menu" role="menu">
				            <li><%= link_to 'Edit profile', edit_author_registration_path, :class => 'navbar-link' %></li>
				            <li><%= link_to('Logout', destroy_author_session_path, :method => :delete) %></li>
				          </ul>
				        </li>
				    <% else %>
                    	<li class="page-scroll">
							<%= link_to "Login", new_author_session_path, :class => 'navbar-link'  %>
						</li>
					<% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
    <div style="height:50px;">
   	</div>
<% if notice %>
	<p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
	<p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= yield %>

</body>
</html>